### ISSUE TITLE
The plugin doesn't work in Kirby 3.4.4

### ISSUE THREAD

**Issue by krisjfr** [sylvainjule/kirby-markdown-field#103]
Nothing change with "type: markdown" instead of "type: textarea"

**Comment by eXpl0it3r** [comment]
Works "fine" for me on Kirby 3.4.4, i.e. when I set `type: markdown` I get a markdown editor

**Comment by krisjfr** [comment]
Thanks for answering. 
I’ve tried again. The only change I see while “type: markdown” is set... is a different font. But no new buttons from Mardown Fields plugin. 
Where can it come from then? What do I miss ?

**Comment by eXpl0it3r** [comment]
The plugin is using the same toolbar as the textarea, as such it might look the same at a first glance.
See the readme on how to configure [buttons](https://github.com/sylvainjule/kirby-markdown-field/blob/master/README.md#33-buttons).

**Comment by krisjfr** [comment]
Hi,
are you saying that the out-of-box settings for “Markdown field” plugin may not be not different from the default blueprint "type: textarea” layout ?
if yes, why not to precise it on github ?

(I’ve used the .zip version => download => unpack)

**Comment by eXpl0it3r** [comment]
What I'm saying is, that if you just superficially look at the panel field, they'll look very similar, since they both use the same toolbar icons.
But once you start adding text and start formatting it, you'll notice that the markdown field will format it differently.

**Comment by krisjfr** [comment]
Nope. 
As I‘ve said, the field “type: markdown” is recognized by Kirby, and the font changes (ugly). But there is no new markdown options availables in formatting bar whatever I do. 
I did test it on “Kirby starter” (so without my multilingual settings). Idem. 
I’ve tried “Editor” and "enhanced-toolbar-link-dialog” plugins. They work “out-of-box” (zip versions).
What’s wrong (with me) ?
:-(

**Comment by eXpl0it3r** [comment]
> But there is no new markdown options availables in formatting bar whatever I do.

What would you expect to show up?

Here's an example I used in my blueprint:

```yml
            fields:
              content:
                label: Content
                type: markdown
                buttons:
                  - headlines
                    - h1
                    - h2
                    - h3
                    - h4
                    - h5
                    - h6
                  - bold
                  - italic
                  - strikethrough
                  - ul
                  - ol
                  - link
                  - email
                  - image
                  - file
                  - pagelink
                  - blockquote
                  - horizontal-rule
```
