### ISSUE TITLE
[next] Default blueprint configuration for file upload

### ISSUE THREAD

**Issue by sebastiangreger** [sylvainjule/kirby-markdown-field#112]
Hi, just kicking the tyres of the `next` branch -- love it already, the plugin API for own button logic in particular! :heart_eyes:

This is not specific to v2, since this is the same in the current version (I just never ran into it, apparently). I noticed that, when using the File button's upload option, the created images don't show up in my files section ...because I've configured a default file blueprint for that section so that all images get assigned `template: image`.

Would there be an easy way to make this configurable in the Markdown Field? Could get messy though, since file uploads might demand different blueprints (e.g. my "Attachments" file section, separate from the one with images, assigns `template: attachment` to PDFs etc.). Of course a hook in the backend is always a fallback option.

**Comment by fabianmichael** [comment]
@sebastiangreger Good question … currently, the editor uses a single field for handling all kinds of files. It might be a better ideas to have dedicated image and file buttons, which could then hold the corresponding config. I will definitely dig into this, as I also stumbled across this, when working with Kirby’s blocks field, because it also sets a blueprint for image uploads. We should find a good solution for this, so it won’t cause any trouble later on.

**Comment by sebastiangreger** [comment]
Maybe something like this?

```
editor:
  label: My markdown editor
  type: markdown
  buttons:
    file:
      template: fileblueprint
```

or

```
editor:
  label: My markdown editor
  type: markdown
  buttons:
    file:
      template:
        image: image
        document: attachment
```

Since this array from the blueprint should be available in the PHP script, this would be a versatile way to control these on a blueprint-to-blueprint basis? I'm thinking that using Kirby's [file types](https://getkirby.com/docs/reference/objects/cms/file/type#all-file-types) would probably be sufficiently granular?
