### ISSUE TITLE
Add "render invisibles/whitespace" option

### ISSUE THREAD

**Issue by fabianmichael** [sylvainjule/kirby-markdown-field#16]
Implement the possibility of making whitespace visible in the editor (basically what every IDE or code editor offers). This also includes line-breaks in Markdown created by adding 2 spaces at the end of a line.

Later on, we can add a button to the toolbar to toggle this feature.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/6f6e5513b7d1e5cb4941c1f820314bf30e459f87

I've made the `invisibles` button an option and detached it from the other buttons. 
Also added an `active` class.

![screen recording 2018-12-23 at 01 43 pm 1](https://user-images.githubusercontent.com/14079751/50383730-ec055680-06b9-11e9-92e2-abcbca38fb0b.gif)

```scss 
/* force alignment of the invisibles button to the right of the toolbar */
.k-markdown-toolbar-buttons-right {
	margin-left: auto;
	border-left: 1px solid $color-light;
}
/* invisibles button styling */
.k-markdown-button-invisibles {
  // ...
  &.active {
    // ...
  }
}
```
