### ISSUE TITLE
[CSS] Add blockquote styling

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-markdown-field#37]
Shouldn't we make it a bit more distinguishable? `$color-dark-grey`?

**Comment by sylvainjule** [comment]
Something like:

![blockquote](https://user-images.githubusercontent.com/14079751/50559543-bf27f380-0cf8-11e9-80ee-373b6d2b593c.jpg)

**Comment by sylvainjule** [comment]
How about:

![01](https://user-images.githubusercontent.com/14079751/50590588-eebb3500-0e8b-11e9-8cd1-ce9ff5c8ba9c.jpg)

or

![02](https://user-images.githubusercontent.com/14079751/50590592-f24ebc00-0e8b-11e9-9651-a0f6071b02d3.jpg)


```scss
.cm-blockquote {
    background: rgba($color-dark, .025); // if background
    border-left: 4px solid rgba($color-dark, .1);
    .cm-formatting-quote {
      padding-left: 2px;
    }
  }
```
