### ISSUE TITLE
Type text and markdown throws error in same blueprint

### ISSUE THREAD

**Issue by jschopplich** [sylvainjule/kirby-markdown-field#40]
The error `The field type "text" does not exist` is thrown when using `type: text` and `type: markdown` on the same blueprint. Can you reproduce?

The following blueprint won't work:
```
preset: page
pages: false

fields:
  intro:
    label: Intro
    type: text

  text:
    label: Text
    type: markdown
```
