### ISSUE TITLE
[Bug] Unable to Override 'buttons' Option from Field Blueprint

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-markdown-field#51]
Let's say I define a *'default_markdown.yml'* field blueprint, which sets out all the buttons I normally want in my standard markdown fields - it looks something like this:

``` yaml
buttons: 
  - headlines
    - h2
    - h3
    - h4
  - bold
  - italic
  - strikethrough
  - horizontal-rule
  - ul
  - ol
  - blockquote
  - code
  - image 
  - file 
  - pagelink
  - link
  - email
```

Now, somewhere else in my site, I'm going to extend this blueprint, wanting to override the 'buttons' option, because I want to use *less* buttons. So, I'd do something like this:

```yaml
byline:
  extends: fields/default_markdown
  buttons:
    - bold
    - italic
    - link
    - pagelink
    - email
```

Unfortunately, when I do this, I still get **all** the buttons from the original field blueprint - not the overridden, shorter list...
