### ISSUE TITLE
Allow custom queries for pagelink, image and file buttons

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-markdown-field#52]
```yaml
markdown:
  type: markdown
  query:
    pagelink: site.children
    image: page.images
    file: page.files.filterBy("type", "!=", "image")
```
