### ISSUE TITLE
The field type "<field_name>" does not exist

### ISSUE THREAD

**Issue by iv-agatha** [sylvainjule/kirby-markdown-field#76]
I'm using Kirby 3.2 and getting this error when using the markdown field. This is what my blueprint looks like:

```
title: Home

tabs:
  content:
    label: Content
    icon: document
    columns:
      - width: 2/3
        fields:
          page_content:
            label: Text
            type: markdown
            size: small
      - width: 1/3
        sections:
          files:
            type: files
```

![image](https://user-images.githubusercontent.com/22304204/60516614-1c9efc00-9cac-11e9-855f-c35b284be8f2.png)
